local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
	-- Snippet para Ecuaciones
	s("eq", {
		t("\\begin{equation}"),
		t({ "", "\t" }),
		i(1),
		t({ "", "\t\\label{eq:" }),
		i(2, "nombre"),
		t("}"),
		t({ "", "\\end{equation}" }),
		i(0),
	}),

	s("balign", {
		t({ "\\begin{align}", "\t" }),
		i(1),
		t(" &= "),
		i(2),
		t({ " \\\\", "\t" }),
		i(3),
		t(" &= "),
		i(4),
		t({ "", "\\end{align}" }),
		i(0),
	}),

	s("system", {
		t({ "\\[", "\\begin{cases}", "\t" }),
		i(1, "eq1"),
		t(" &= "),
		i(2, "res1"),
		t({ " \\\\", "\t" }),
		i(3, "eq2"),
		t(" &= "),
		i(4, "res2"),
		t({ "", "\\end{cases}", "\\]" }),
		i(0),
	}),

	-- Snippet para Sistema de Ecuaciones con Aligned
	s("sys", {
		t({ "\\[", "\\left\\{", "\t\\begin{aligned}", "\t\t" }),
		i(1, "x + y"),
		t(" &= "),
		i(2, "5"),
		t({ " \\\\", "\t\t" }),
		i(3, "2x - y"),
		t(" &= "),
		i(4, "1"),
		t({ "", "\t\\end{aligned}", "\\right.", "\\]" }),
		i(0),
	}),

	-- Sistema con numeración única (Todo el bloque)
	s("sysnum", {
		t({ "\\begin{equation}", "\t\\left\\{", "\t\\begin{aligned}", "\t\t" }),
		i(1, "x + y"),
		t(" &= "),
		i(2, "5"),
		t({ " \\\\", "\t\t" }),
		i(3, "2x - y"),
		t(" &= "),
		i(4, "1"),
		t({ "", "\t\\end{aligned}", "\t\\right.", "\t\\label{eq:" }),
		i(5, "sistema1"),
		t("}"),
		t({ "", "\\end{equation}" }),
		i(0),
	}),

	-- Ecuaciones alineadas con numeracion individual (cada ecuacion)
	s("sysind", {
		t({ "\\begin{align}", "\t" }),
		i(1, "x + y"),
		t(" &= "),
		i(2, "5"),
		t(" \\label{eq:"),
		i(3, "ec1"),
		t({ "} \\\\", "\t" }),
		i(4, "2x - y"),
		t(" &= "),
		i(5, "1"),
		t(" \\label{eq:"),
		i(6, "ec2"),
		t("}"),
		t({ "", "\\end{align}" }),
		i(0),
	}),

	-- Sistema con llave y numeros individuales. Requiere \usepackage{empheq} en el preámbulo
	s("syskeyind", {
		t({ "\\begin{empheq}[left=\\empheqlbrace]{align}", "\t" }),
		i(1, "x + y"),
		t(" &= "),
		i(2, "5"),
		t(" \\label{eq:"),
		i(3, "ec1"),
		t({ "} \\\\", "\t" }),
		i(4, "2x - y"),
		t(" &= "),
		i(5, "1"),
		t(" \\label{eq:"),
		i(6, "ec2"),
		t("}"),
		t({ "", "\\end{empheq}" }),
		i(0),
	}),

	s("mat", {
		t("\\begin{"),
		i(1, "p"),
		t("matrix}"),
		t({ "", "\t" }),
		i(2, "elemento"),
		t(" & "),
		i(3),
		t({ " \\\\", "\t" }),
		i(4),
		t(" & "),
		i(5),
		t({ "", "\\end{" }),
		f(function(args)
			return args[1][1]
		end, { 1 }),
		t("matrix}"),
		i(0),
	}),

	-- Matriz de 2x2
	s("mat2", {
		t({ "\\begin{pmatrix}", "\t" }),
		i(1, "a"),
		t(" & "),
		i(2, "b"),
		t({ " \\\\", "\t" }),
		i(3, "c"),
		t(" & "),
		i(4, "d"),
		t({ "", "\\end{pmatrix}" }),
		i(0),
	}),

	-- Matriz de 3x3
	s("mat3", {
		t({ "\\begin{pmatrix}", "\t" }),
		i(1, "r1c1"),
		t(" & "),
		i(2, "r1c2"),
		t(" & "),
		i(3, "r1c3"),
		t({ " \\\\", "\t" }),
		i(4, "r2c1"),
		t(" & "),
		i(5, "r2c2"),
		t(" & "),
		i(6, "r2c3"),
		t({ " \\\\", "\t" }),
		i(7, "r3c1"),
		t(" & "),
		i(8, "r3c2"),
		t(" & "),
		i(9, "r3c3"),
		t({ "", "\\end{pmatrix}" }),
		i(0),
	}),

	-- Snippet para Tablas Pro (con [H] y booktabs)
	s("table", {
		t({ "\\begin{table}[H]", "\t\\centering", "\t\\caption{" }),
		i(1, "título"),
		t("}"),
		t({ "", "\t\\label{tab:" }),
		i(2, "referencia"),
		t("}"),
		t({ "", "\t\\begin{tabular}{" }),
		i(3, "cll"),
		t("}"),
		t({ "", "\t\t\\toprule", "\t\t" }),
		i(4, "Encabezado & Columna & Columna"),
		t({ " \\\\", "\t\t\\midrule", "\t\t" }),
		i(5, "Dato & Dato & Dato"),
		t({ " \\\\", "\t\t\\bottomrule", "\t\t\\end{tabular}", "\\end{table}" }),
		i(0),
	}),

	s("matsum", {
		t({ "\\[", "\\begin{pmatrix}", "\t" }),
		i(1, "a11"),
		t(" & "),
		i(2, "a12"),
		t({ " \\\\", "\t" }),
		i(3, "a21"),
		t(" & "),
		i(4, "a22"),
		t({ "", "\\end{pmatrix}", "+", "\\begin{pmatrix}", "\t" }),
		i(5, "b11"),
		t(" & "),
		i(6, "b12"),
		t({ " \\\\", "\t" }),
		i(7, "b21"),
		t(" & "),
		i(8, "b22"),
		t({ "", "\\end{pmatrix}", "=", "\\begin{pmatrix}", "\t" }),
		i(9, "res11"),
		t(" & "),
		i(10, "res12"),
		t({ " \\\\", "\t" }),
		i(11, "res21"),
		t(" & "),
		i(12, "res22"),
		t({ "", "\\end{pmatrix}", "\\]" }),
		i(0),
	}),

	-- Snippet para Lógica Formal (útil para la UNCuyo)
	s("logic", {
		t("\\[ "),
		i(1, "p \\implies q"),
		t(" \\]"),
	}),

	-- Snippet para Imágenes
	s("image", {
		t({ "\\begin{figure}[H]", "\t\\centering", "\t\\includegraphics[width=" }),
		i(1, "0.8"),
		t("\\textwidth]{"),
		i(2, "nombre_archivo"),
		t("}"),
		t({ "", "\t\\caption{" }),
		i(3, "descripción"),
		t("}"),
		t({ "", "\t\\label{fig:" }),
		i(4, "ref"),
		t("}"),
		t({ "", "\\end{figure}" }),
		i(0),
	}),
}
